name: pra_s_application6
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.5
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  flutter_svg_provider: ^1.0.3
  intl: ^0.17.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Mulish
      fonts: 
        - asset: assets/fonts/MulishExtraBold.ttf
          weight: 800
        - asset: assets/fonts/MulishRomanBold.ttf
          weight: 700
        - asset: assets/fonts/MulishRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/MulishItalicRegular.ttf
          weight: 400
        - asset: assets/fonts/MulishRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/MulishBold.ttf
          weight: 700
        - asset: assets/fonts/MulishMedium.ttf
          weight: 500
        - asset: assets/fonts/MulishSemiBold.ttf
          weight: 600
        - asset: assets/fonts/MulishBlack.ttf
          weight: 900
    - family: Abel
      fonts: 
        - asset: assets/fonts/AbelRegular.ttf
          weight: 400
